package com.xin.util;

import android.content.Intent;

public class IntentPrint {
	public static String flagsToString(Intent intent){
		return flagsToString(intent.getFlags());
	}
	public static String flagsToString(int flag){
		StringBuffer buffer=new StringBuffer();
		boolean first=true;
		for(int i=0;i<ALL_FLAG.length;i++){
			if((flag&ALL_FLAG[i])==ALL_FLAG[i]){
				if(first){
					first=false;
				}else{
					buffer.append(", ");
				}
				buffer.append(ALL_FLAG_LABEL[i]);
				
			}
		}
		return buffer.toString();
	}
	public static final int[] ALL_FLAG={
	Intent.FLAG_GRANT_READ_URI_PERMISSION,
	Intent.FLAG_GRANT_WRITE_URI_PERMISSION,
	Intent.FLAG_DEBUG_LOG_RESOLUTION,
	Intent.FLAG_FROM_BACKGROUND,
	Intent.FLAG_ACTIVITY_BROUGHT_TO_FRONT,
	Intent.FLAG_ACTIVITY_CLEAR_TASK,
	Intent.FLAG_ACTIVITY_CLEAR_TOP,
	Intent.FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET,
	Intent.FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS,
	Intent.FLAG_ACTIVITY_FORWARD_RESULT,
	Intent.FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY,
	Intent.FLAG_ACTIVITY_MULTIPLE_TASK,
	Intent.FLAG_ACTIVITY_NEW_TASK,
	Intent.FLAG_ACTIVITY_NO_ANIMATION,
	Intent.FLAG_ACTIVITY_NO_HISTORY,
	Intent.FLAG_ACTIVITY_NO_USER_ACTION,
	Intent.FLAG_ACTIVITY_PREVIOUS_IS_TOP,
	Intent.FLAG_ACTIVITY_RESET_TASK_IF_NEEDED,
	Intent.FLAG_ACTIVITY_REORDER_TO_FRONT,
	Intent.FLAG_ACTIVITY_SINGLE_TOP,
	Intent.FLAG_ACTIVITY_TASK_ON_HOME,
	Intent.FLAG_RECEIVER_REGISTERED_ONLY
	};
	public static final String[] ALL_FLAG_LABEL={
		"FLAG_GRANT_READ_URI_PERMISSION",
		"FLAG_GRANT_WRITE_URI_PERMISSION",
		"FLAG_DEBUG_LOG_RESOLUTION",
		"FLAG_FROM_BACKGROUND",
		"FLAG_ACTIVITY_BROUGHT_TO_FRONT",
		"FLAG_ACTIVITY_CLEAR_TASK",
		"FLAG_ACTIVITY_CLEAR_TOP",
		"FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET",
		"FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS",
		"FLAG_ACTIVITY_FORWARD_RESULT",
		"FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY",
		"FLAG_ACTIVITY_MULTIPLE_TASK",
		"FLAG_ACTIVITY_NEW_TASK",
		"FLAG_ACTIVITY_NO_ANIMATION",
		"FLAG_ACTIVITY_NO_HISTORY",
		"FLAG_ACTIVITY_NO_USER_ACTION",
		"FLAG_ACTIVITY_PREVIOUS_IS_TOP",
		"FLAG_ACTIVITY_RESET_TASK_IF_NEEDED",
		"FLAG_ACTIVITY_REORDER_TO_FRONT",
		"FLAG_ACTIVITY_SINGLE_TOP",
		"FLAG_ACTIVITY_TASK_ON_HOME",
		"FLAG_RECEIVER_REGISTERED_ONLY"
	};
}
